# Generated by Django 2.2.5 on 2021-09-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20210925_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ManyToManyField(to='rooms.RoomType'),
        ),
    ]
