# Generated by Django 2.2.5 on 2021-12-02 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_auto_20211020_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='rooms',
            new_name='room',
        ),
    ]
